// Results Dashboard Page Component

import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAnalysis } from '../context/AnalysisContext';

import { StudentProfileCard } from '../components/StudentProfileCard';
import { MatchScoreCard } from '../components/MatchScoreCard';
import { SkillGapCard } from '../components/SkillGapCard';
import { RoadmapCard } from '../components/RoadmapCard';
import { InterviewCard } from '../components/InterviewCard';
import { PipelineSummaryCard } from '../components/PipelineSummaryCard';

export const ResultsPage: React.FC = () => {
  const { analysisResult, resetAnalysis } = useAnalysis();
  const navigate = useNavigate();

  // Redirect to home if no analysis results exist
  useEffect(() => {
    if (!analysisResult) {
      navigate('/');
    }
  }, [analysisResult, navigate]);

  if (!analysisResult) {
    return null;
  }

  const handleBack = () => {
    resetAnalysis();
    navigate('/');
  };

  const handleExportJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(analysisResult, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    
    const candidateName = analysisResult.student_profile?.name || "candidate";
    const filename = `placement_analysis_${candidateName.toLowerCase().replace(/\s+/g, '_')}.json`;
    
    downloadAnchor.setAttribute("download", filename);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handlePrint = () => {
    window.print();
  };

  const candidateName = analysisResult.student_profile?.name || "Student";
  const roleTitle = analysisResult.hiring_requirements?.role_title || "Target Role";

  return (
    <div style={containerStyle}>
      {/* Dashboard Top Header Control Panel */}
      <div style={headerControlStyle} className="no-print">
        <button className="btn btn-secondary" onClick={handleBack}>
          ← Analyze Another Fit
        </button>
        <div style={actionButtonsGroupStyle}>
          <button className="btn btn-secondary" onClick={handleExportJSON}>
            📥 Export JSON Payload
          </button>
          <button className="btn btn-primary" onClick={handlePrint}>
            🖨️ Download Report (Print)
          </button>
        </div>
      </div>

      {/* Main Print Title (only visible on print output) */}
      <div style={printHeaderStyle}>
        <h2>Placement readiness Report</h2>
        <p>Candidate: {candidateName} | Target Job: {roleTitle}</p>
        <p>Generated by: Placement Intelligence Platform</p>
      </div>

      <div style={dashboardTitleContainerStyle}>
        <h2 style={titleStyle}>Placement Readiness Dashboard</h2>
        <p style={subTitleStyle}>
          Comprehensive multi-agent readiness evaluation for <strong>{candidateName}</strong> applying for <strong>{roleTitle}</strong>.
        </p>
      </div>

      {/* Grid Dashboard Layout */}
      <div className="results-grid">
        {/* Section 1: Student Profile */}
        {analysisResult.student_profile && (
          <StudentProfileCard profile={analysisResult.student_profile} />
        )}

        {/* Section 2: Match Analysis */}
        {analysisResult.match_result && (
          <MatchScoreCard matchResult={analysisResult.match_result} />
        )}

        {/* Section 3: Skill Gap Report */}
        {analysisResult.skill_gap_report && analysisResult.match_result && (
          <SkillGapCard 
            gapReport={analysisResult.skill_gap_report} 
            matchResult={analysisResult.match_result} 
          />
        )}

        {/* Section 4: Career Roadmap */}
        {analysisResult.career_roadmap && analysisResult.match_result && analysisResult.skill_gap_report && (
          <RoadmapCard 
            roadmap={analysisResult.career_roadmap} 
            matchResult={analysisResult.match_result}
            gapReport={analysisResult.skill_gap_report}
          />
        )}

        {/* Section 5: Interview Preparation */}
        {analysisResult.interview_report && (
          <div className="results-full-width">
            <InterviewCard interviewReport={analysisResult.interview_report} />
          </div>
        )}

        {/* Section 6: Pipeline Diagnostic Summary */}
        <div className="results-full-width">
          <PipelineSummaryCard result={analysisResult} />
        </div>
      </div>
    </div>
  );
};

const containerStyle: React.CSSProperties = {
  width: '100%',
  display: 'flex',
  flexDirection: 'column',
};

const headerControlStyle: React.CSSProperties = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: '28px',
  flexWrap: 'wrap',
  gap: '16px',
};

const actionButtonsGroupStyle: React.CSSProperties = {
  display: 'flex',
  gap: '12px',
};

const dashboardTitleContainerStyle: React.CSSProperties = {
  marginBottom: '24px',
};

const titleStyle: React.CSSProperties = {
  fontSize: '2rem',
  marginBottom: '8px',
};

const subTitleStyle: React.CSSProperties = {
  color: 'var(--text-secondary)',
  fontSize: '1rem',
  lineHeight: 1.5,
};

const printHeaderStyle: React.CSSProperties = {
  display: 'none', // hidden on browser viewport, shown on print via @media print in index.css
};
